version: '2'

services:

  mongo:
    image: mongo:latest
    container_name: database-mongo
    hostname: mongo
    ports:
      - "27017:27017"
    environment:
      TZ: "${TZ}"
    volumes:
      - "${MONGO_DATA}:/data/db"

  node:
    image: node
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: microservice-node
    hostname: node
    environment:
      TZ: "${TZ}"
      JWT_SECRET: "${JWT_SECRET}"
    ports:
      - "8000-8010:8000-8010"
      - "8100-8110:8100-8110"
    volumes:
      - "${WWW_DATA}:/var/www/html"
      - "${NODE_SERVICES_ENTRYPOINT}:/entrypoint.sh"
    command: >
       sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime &&
       echo $TZ > /etc/timezone &&
       chmod 777 /entrypoint.sh"
    links:
      - mongo
    depends_on:
      - mongo

  web-proxy:
    image: web-proxy
    build:
      context: .
      dockerfile: Dockerfile.web-proxy
      args:
        timezone: "${TZ}"
    container_name: gateway-openresty
    hostname: web-proxy
    environment:
      JWT_SECRET: "${JWT_SECRET}"
    ports:
      - "8080:8080"
    volumes:
      - "${OPENRESTY_NGINX_CONF}:/nginx.conf"
      - ./conf/openresty/lua/bearer.lua:/bearer.lua
    links:
      - node
    depends_on:
      - node

  web:
    image: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: server-nginx
    ports:
      - "80:80"
    environment:
      TZ: "${TZ}"
    volumes:
      - "${WWW_DATA}:/var/www/html"
      - "${NGINX_HOSTS_CONF}:/etc/nginx/conf.d"
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - node
      - web-proxy
    depends_on:
      - node
      - web-proxy
