FROM node

MAINTAINER "Diego Wagner" <diegowagner4@gmail.com>

RUN DEBIAN_FRONTEND=noninteractive apt-get update -q \
    && DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        git

RUN npm install -g \
    gulp \
    bower \
    polymer-cli \
    pm2

WORKDIR /var/www/html

RUN touch /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

#CMD ["cd", "/var/www/html/dsc-api-auth"]
#CMD ["npm", "start"]
#CMD ["pm2", "logs"]
